### ISSUE TITLE
Rename project

### ISSUE THREAD

**Issue by nixolas1** [zoff-music/Zoff#108]
Rename Zöff to something easily communicated.
And get a new international domain maybe?
 - [ ] radiolist.me
 - [ ] livemix.me
 - [ ] instamix.me

**Comment by nixolas1** [comment]
I came up with something like 
livemix
youmix
instamix
mixtube
giantvaginarightintheface,ch

**Comment by lqasse** [comment]
giantvaginarightintheface,ch +1

**Comment by kasperrt** [comment]
Vote for getting zoff.io instead of renaming

**Comment by lqasse** [comment]
Er .com ledig?

**Comment by kasperrt** [comment]
No, costs $20.000 for it
