### ISSUE TITLE
MongoDB to mongoose

### ISSUE THREAD

**Issue by dsalcedo** [zoff-music/Zoff#131]
Why not change mongojs to Mongoose ? May be this change can help you for create code more clean and efficient ;) :+1:

**Comment by kasperrt** [comment]
Yes, but rhats not the issue here, the issue is that the disconnect isnt firing

On 10 Aug 2015 17:03, "J. Daniel Salcedo Sambrano" <notifications@github.com> wrote:Why not change mongojs to Mongoose ? May be this change can help you for create code more clean and efficient ;)

**Comment by dsalcedo** [comment]
can you share me the scheme for run in mi local and test it ?

**Comment by kasperrt** [comment]
You need the server.js, and the node_modules in the serverfolder.

On 11 Aug 2015 17:50, "J. Daniel Salcedo Sambrano" <notifications@github.com> wrote:can you share me the scheme for run in mi local and test it ?
