### ISSUE TITLE
Redesign frontpage

### ISSUE THREAD

**Issue by kasperrt** [zoff-music/Zoff#134]
Have frontpage with bigger searchbar. 

Maybe timer where random playlistname featured on the frontpage appear as placeholder for the channel input?

Maybe blurred picture with low opacity as "background" behind channel input field, belonging to the channel thats name is picked as placeholder?

**Comment by nixolas1** [comment]
See https://github.com/zoff-music/Zoff/tree/fancy for startpoint for this

**Comment by kasperrt** [comment]
Go-go you can do it!

**Comment by nixolas1** [comment]
No time! My people needs me!
