### ISSUE TITLE
 Cannot modify header 

### ISSUE THREAD

**Issue by ulamnet** [zoff-music/Zoff#142]
Warning: Cannot modify header information - headers already sent by (output started at /home/musicply/public_html/index.php:2) in /home/musicply/public_html/index.php on line 4

**Comment by ulamnet** [comment]
http://passionishoes.com/dans/ not working .

**Comment by kasperrt** [comment]
I cant reproduse the error, have you changed any code from the repo? And do you use PHP, and the zoff-server on the backend?
--

KasperRT

On Jan 9, 2016 12:15, ulamnet <notifications@github.com> wrote:

Warning: Cannot modify header information - headers already sent by (output started at /home/musicply/public_html/indexphp:2) in /home/musicply/public_html/indexphp on line 4

**Comment by ulamnet** [comment]
how to install server ?

**Comment by kasperrt** [comment]
Server is located at https://github.com/zoff-music/zoff-server. Follow the README.md there.
