### ISSUE TITLE
Can't pause playback

### ISSUE THREAD

**Issue by madanh** [zoff-music/Zoff#148]
Firefox 45.0 on Linux Mint 17.1. Clicking in the vid produces and animation of a circle with pause sign, but not much more else.

Dunno if that's a bug or a feature though :)

**Comment by kasperrt** [comment]
This wad thought as a feature, but we're rewerting it as soon as we're home from a short holliday :)

-- 

Kasper Rynning-Tønnesen
+97 74 04 27

On Mar 17, 2016 9:53 PM, Hennadii Madan <notifications@github.com> wrote:

Firefox 45.0 on Linux Mint 17.1. Clicking in the vid produces and animation of a circle with pause sign, but not much more else.

Dunno if that's a bug or a feature though :)

**Comment by madanh** [comment]
K thx:) gud day!
