### ISSUE TITLE
Doesn't create rooms

### ISSUE THREAD

**Issue by Rekkisomo** [zoff-music/Zoff#150]
Whenever I try to create a room, it always says `https://domain-here.com/chill/php/index.php` not found (404)

**Comment by Rekkisomo** [comment]
im not sure how to properly run it, but its running under Apache2

**Comment by kasperrt** [comment]
Do you have PHP installed? And have you changed any of the files?

**Comment by kasperrt** [comment]
@Rekkisomo you have to set the AllowOverride flag to All in your 000-default.conf file for Apache. It should now be added in the README.md.

Hope this helps

**Comment by Rekkisomo** [comment]
It says that AllowOverride isn't allowed there :\

Just checked, AllowOverride is nowhere in that file.

**Comment by kasperrt** [comment]
You have to add 

```
<Directory "/var/www/html">
    AllowOverride All
</Directory>
```

Example of a ```000-default.conf``` : 

```
<VirtualHost *:80>
	ServerAdmin webmaster@localhost
	DocumentRoot /var/www/html

	ErrorLog ${APACHE_LOG_DIR}/error.log
	CustomLog ${APACHE_LOG_DIR}/access.log combined

	<Directory "/var/www/html">
		AllowOverride All
	</Directory>

</VirtualHost>
```

**Comment by Rekkisomo** [comment]
:( Still happening. Could it possibly be something else? The only errors in the console is the 404 errors that I stated above.

**Comment by Rekkisomo** [comment]
I should also note that yes, I restarted the apache2 server & the base Zoff server is running.

**Comment by kasperrt** [comment]
Is it still saying that it's not allowed there? Can you post your apache2 conf-file?

**Comment by kasperrt** [comment]
And have you enabled mod_rewrite? (This can be done with ```$ sudo a2enmod rewrite```

**Comment by Rekkisomo** [comment]
```
<VirtualHost *:80>
        ServerName curitzjt.cf

        ServerAdmin curtis@curitzjt.cf
        DocumentRoot /var/www/html

        <Directory "/var/www/html">
                AllowOverride All
        </Directory>
        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined
</VirtualHost>
```

I also enabled rewrite just then, still no luck :c

**Comment by kasperrt** [comment]
And remembered to restart Apache2?

**Comment by Rekkisomo** [comment]
Yes

**Comment by Rekkisomo** [comment]
Aww crap! Sorry to waste your time, I was missing `.htaccess` xP


I am, super sorry!

**Comment by Rekkisomo** [comment]
Crud, I got it to create the room and show the UI! But it sits at `Loading...` (FYI: Yes, the Zoff server is running and configured properly)

**Comment by Rekkisomo** [comment]
```
Uncaught TypeError: Cannot read property 'emit' of undefined
```
If this helps

**Comment by kasperrt** [comment]
Is the socket.io library being loaded? It's put to load locally from static/dist/lib/

**Comment by Rekkisomo** [comment]
http://i.imgur.com/AIiTie6.png mhm

**Comment by kasperrt** [comment]
Have you pulled the latest version? 

Since you're getting the ```Cannot read property 'emit' of undefined``` error, it means that the socket variable isn't assigned to a socket.io object, and a connection to the server hasn't been established.

**Comment by kasperrt** [comment]
Have you tried running it on localhost, instead of an external hostname?

**Comment by Rekkisomo** [comment]
I'll try that now :+1:

**Comment by kasperrt** [comment]
I've got it working on both localhost and an external hostname. Is there maybe some files you're missing, or something that you've changed?

**Comment by Rekkisomo** [comment]
All I've changed is the redirects (e.g. remote.whatever.whatever)

**Comment by kasperrt** [comment]
Is there still errors if you do a clean clone of the project, and run that from your apache2 web-folder? I can't seem to reproduce your problem..

**Comment by kasperrt** [comment]
And do you have the webserver installed on some subfolder of the network, instead of the root of the hostname?

**Comment by Rekkisomo** [comment]
its all in `/var/www/html`, so no. I'm still trying to get Apache2 to work on localhost >//<

**Comment by kasperrt** [comment]
The apache2 root-folder might also be ```/var/www/``` depending on your install.

If you just uncomment the ServerName in 000-default.conf, it should use localhost by default.

**Comment by Rekkisomo** [comment]
I'm running it on a server right now

**Comment by kasperrt** [comment]
Is it external? If so, whats the url, so I can see if I figure it out?

**Comment by Rekkisomo** [comment]
https://rdo.curitzjt.cf/

Im currently repulling and resetting the socket server

**Comment by kasperrt** [comment]
https://rdo.curitzjt.cf/te/ is working for me. But you haven't specified the certificate to be used serverside.

**Comment by Rekkisomo** [comment]
Well repulling seemed to work 0.o

Its also using Cloudflare's DNS & A generated key in `/etc/apache2/ssl`

**Comment by Rekkisomo** [comment]
Im positive that it's an easy fix though :D

**Comment by Rekkisomo** [comment]
Well, thanks :smile:

**Comment by kasperrt** [comment]
You're going to have some issues when navigating from one page to another, because of the horrendous handling of "one-page-appification", where elements are being replaced depending on their index of the whole page's array, so you're probably going to have the 


still in the head. 

A fix will come for this soon.. hopefully
