### ISSUE TITLE
Cannot find module 'cert_config.js'

### ISSUE THREAD

**Issue by kamidipreetham** [zoff-music/zoff#227]
After 'npm install', npm start gives this error

![zoff](https://user-images.githubusercontent.com/9149028/32663862-6f1f8a0a-c655-11e7-9cb2-ce55ecb078d0.png)

**Comment by kasperrt** [comment]
Pull the newest version from master now, I've added a more descriptive error-message on that crash.

The error is caused by the server not finding certain config-files, which didn't have a catch on crash to tell what is missing. Have a look in the /server/config/ file and the *.example.js files
